### ISSUE TITLE
For me this breaks the file stream and the gulp task.

### ISSUE THREAD

**Issue by jkarttunen** [adamayres/gulp-filelog#4] opened 2014-10-08 21:45 UTC
Node v0.10.23
"gulp": "~3.8.8",

**Comment by spy4x** [comment] 2014-10-15 10:25
+1

**Comment by adamayres** [comment] 2014-10-18 22:52
I am not able to reproduce, can you provide a code snippet? I used this:

``` javascript
var gulp = require('gulp');
var filelog = require('gulp-filelog');
var svgicons2svgfont = require('gulp-svgicons2svgfont');

gulp.task('default', function () {
    gulp.src('*.svg', { buffer: false })
        .pipe(filelog()) // works fine here
        .pipe(svgicons2svgfont({
            fontName: 'myfont'
         }))
        .pipe(filelog()) // and here
        .pipe(gulp.dest("./dist"));
});
```

**Comment by adamayres** [comment] 2014-11-03 20:01
Closing, please feel free to re-open with some examples.

**Closed as completed by adamayres** 2014-11-03 20:01 UTC
